# Podman aliases - tương tự Docker nhưng dùng Podman
alias pcu "podman-compose up -d"
alias pcd "podman-compose down"
alias pps "podman ps -a"
alias pe "podman exec -it"
alias prm "podman rm -f"
alias pr "podman restart"
alias prma "podman rm -f (podman ps -aq)"
alias plf "podman logs -f"
alias pimg "podman images"
alias prmi "podman rmi"
alias ppull "podman pull"
alias pbuild "podman build"
alias prun "podman run"
alias pstop "podman stop"
alias pstart "podman start"
alias pinspect "podman inspect"
alias pnw "podman network"
alias pvolume "podman volume"
alias pms "podman machine start"